Algoritmo "Entrada e Saida de dados"
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/09/2023
// Seção de Declarações das variáveis 
    nome: caractere
    nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Escreva seu nome:")
   leia(nome)
   escreval("Escreva a idade de seu amigo:")
   leia(nota)
   
   escreval("O nome digitado foi: ", nome)
   escreval("A idade digitada foi: ", nota)

Fimalgoritmo